services:
  postgres:
    container_name: threads-db
    image: postgres
    ports:
      - "5555:5432"
    volumes:
      - postgress_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: thread_postgress
      POSTGRES_DB: threads
      POSTGRES_PASSWORD: password

volumes:
  postgress_data:
